create table registered_user (
  id int8 generated by default as identity,
  address varchar(255),
  name varchar(255),
  phone_number int8,
  surname varchar(255),
  primary key (id)
);

create table users (
  session_id int8 generated by default as identity,
  registered_user_id int8,
  primary key (session_id)
);

alter table if exists users add constraint FKmgx1nvifc47gmkq13y1vmcnte foreign key (registered_user_id) references registered_user
